spring.application.name=products
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:products}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:products}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health

products.security.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION:file:./config/jwt/generated/dev-public-key.pem}
products.security.jwt.issuer=${JWT_ISSUER:products-challenge-dev}
products.security.jwt.audience=${JWT_AUDIENCE:products-api}
