spring.application.name=products
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:products}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:products}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
