CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT chk_products_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    value NUMERIC(19, 2) NOT NULL,
    init_date DATE NOT NULL,
    end_date DATE,
    validity DATERANGE GENERATED ALWAYS AS (
        daterange(
            init_date,
            CASE
                WHEN end_date IS NULL THEN NULL
                ELSE end_date + 1
            END,
            '[)'
        )
    ) STORED NOT NULL,

    CONSTRAINT pk_prices PRIMARY KEY (id),
    CONSTRAINT fk_prices_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_prices_value_positive CHECK (value > 0),
    CONSTRAINT chk_prices_dates CHECK (end_date IS NULL OR init_date < end_date),
    CONSTRAINT ex_prices_product_validity
        EXCLUDE USING gist (
            product_id WITH =,
            validity WITH &&
        )
);

CREATE INDEX idx_prices_product_history
    ON prices (product_id, init_date, id);
